### ISSUE TITLE
Are the `locs` ranges refered here really any indel greater than width of 1?

### ISSUE THREAD

**Issue by leipzig** [rcastelo/VariantFiltering#6]
https://github.com/rcastelo/VariantFiltering/blob/master/R/annotationEngine.R#L801-L802
```
Error in .loc2SNPid(annObj, variantsGR[masksnp], BPPARAM = BPPARAM) : 
  all ranges in 'locs' must be of width 1
```

That seems awfully strict. How can I tell VariantFiltering to simply not annotate those loci?

**Comment by rcastelo** [comment]
i just updated the github repo, i'm still using svn as first devel repository and this is a mirror that i update "manually" when i think about it :) i plan to switch to github soon, but i'm saying this just in case you notice that the lines you mention now they do not match exactly anymore. regarding the issue, this is an internal function called by the annotateVariants() method with an SNPlocs object. this kind of object is loaded via one of the SNPlocs Bioconductor annotation packages and their purpose is simply to annotate dbSNP identifiers to SNVs in given positions. if you want to annotate dbSNP identifiers to variants that are not SNVs, you need to provide an XtraSNPlocs object via an annotation package such as XtraSNPlocs.Hsapiens.dbSNP144.GRCh38. this will force the method annotateVariants() to call the private function .loc2XtraSNPid() which will handle the annotation of non-SNVs. however, the user is not supposed to call these private functions, but this should be done when creating the VariantFilteringParam object, by setting the argument snpdb as follows, e.g.,

snpdb=list("SNPlocs.Hsapiens.dbSNP144.GRCh37", "XtraSNPlocs.Hsapiens.dbSNP144.GRCh37")

actually for this kind of questions, it is better to use the BioC support site at http://support.bioconductor .org. if you haven't done it in the past, please take a look first to the posting guide at http://bioconductor.org/help/support/posting-guide

this github repo contains the devel version of the package and therefore issues here should be more related to features under development.

**Comment by rcastelo** [comment]
i forgot to tell, if you want VariantFiltering to simply not annotate dbSNP identifiers at all, just set snpdb=list() when calling VariantFilteringParam()
